version: "3.8"
   
services:
    pgdb:
        image: postgres
        container_name: showcase_pgdb
        environment:
            - POSTGRES_DB=showcase
            - POSTGRES_USER=showcase
            - POSTGRES_PASSWORD=showcase
        volumes:
            - pgdata:/var/lib/postgresql/data/
    django:
        build: .
        container_name: django
        # command: ./runserver.sh
        command: >
            /bin/bash -c "
                sleep 5;
                python manage.py makemigrations;
                python manage.py migrate;
                python manage.py runserver 0.0.0.0:8000;
            "
        volumes:
            - .:/showcase
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - DB_USER=showcase
            - DB_PASSWORD=showcase
            - DB_NAME=showcase
            - DB_PORT=5432
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        # command: celery -A showcase worker -l INFO
        command: >
            /bin/bash -c "
                sleep 5;
                celery -A showcase worker -l INFO;
            "
        volumes:
            - .:/showcase
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    
    

    redis:
        image: "redis:alpine"
        ports:
            - "6378:6379"

    celery-beat:
        build: .
        # command: celery -A showcase beat -l info
        command: >
            /bin/bash -c "
                sleep 7;
                celery -A showcase beat -l INFO;
            "
        volumes:
            - .:/showcase
        depends_on:
        - pgdb
        - redis
    
    flower:
        build: .
        # command: flower -A showcase
        command: >
            /bin/bash -c "
                sleep 7;
                celery -A showcase flower --port=5555 --persistent=True;
            "
        volumes:
        - .:/showcase
        ports:
        - "5555:5555"
        depends_on:
        - pgdb
        - redis

volumes:
    pgdata: