# Generated by Django 4.0.6 on 2022-07-09 17:05

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from datetime import datetime




def createsuperuser(apps, schema_editor):
    User = get_user_model()
    User.objects.get_or_create(
        email="asfaw.ayalkibet@gmail.com",
        username="asfaw",
        password=make_password("password"),
        last_login=datetime.now(),
        is_staff=True,
        is_superuser=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createsuperuser, reverse_code=migrations.RunPython.noop),

    ]
